[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
satik = "BcmqgRT4uiiCq4q64e4vGRyLRSRRV1na3aAkDaq7ABRf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/suraj/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
