[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
satik = "8Vr9DzSPk98B21qPmFba2mzb75kbTcmUF86YoBwmBxhp"

[programs.localnet]
satik = "5yGpHM8VQdAcw4tPYe8aS7asnsxeJgd5mfzFABD441cB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/suraj/projects/solana/satik/keypair.json"

[scripts]
index = "bun run tests/index.ts"
test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
