[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
satik = "C86he5HKmQvHpLH2zoZgozwBCm9wkGBYsjBNhmjwNDTU"

[programs.localnet]
satik = "C86he5HKmQvHpLH2zoZgozwBCm9wkGBYsjBNhmjwNDTU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/suraj/projects/solana/satik/keypair.json"

[scripts]
test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
