[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
satik = "83FvGohXr2jykhvbacKPvgeCpTGjanmC2vVjgWHZgEcS"

[programs.localnet]
satik = "83FvGohXr2jykhvbacKPvgeCpTGjanmC2vVjgWHZgEcS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/viristo/.config/solana/id.json"

[scripts]
test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
