[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
satik = "5yGpHM8VQdAcw4tPYe8aS7asnsxeJgd5mfzFABD441cB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/suraj/projects/solana/satik/keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
