[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
satik = "EVsYvVjhpgYr9RExmu6sn1Hi5fCufyFfXhwkBZcuy6ah"

[programs.localnet]
satik = "EVsYvVjhpgYr9RExmu6sn1Hi5fCufyFfXhwkBZcuy6ah"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/viristo/.config/solana/id.json"

[scripts]
index = "bun run src_js/index.ts"
oracle = "bun run src_js/oracle.ts"
test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
