[toolchain]

[features]
seeds = false
skip-lint = false


[programs.localnet]
satik = "4L1SsEXGTzAjW7ajdm5xgqsCvi1jnRHLNsqytjiKdMeK"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/viristo/.config/solana/id.json"

[scripts]
test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
