[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
satik = "BkF89c2Cjm2KBvgWF9BQe8wTuPJ3LKtqNPZh1j38A2KZ"

[programs.localnet]
satik = "H4VNzSEj54eSpvtLJ5JFuaxeXryeMQS9kPL1m4kE1Z3E"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/viristo/.config/solana/id.json"

[scripts]
index = "bun run index.ts"
test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
